version: '3'
services:
  jenkins:
     container_name: jenkins
     image: jenkinsci/jenkins
     ports:
      - "8080:8080"
     volumes:
      - C:/Users/LENOVO/Documents/Estudio/jenkins/jenkins_home:/var/jenkins_home
     networks:
      - net
networks:
   net:
